global:
  scrape_timeout_offset: 500ms
  min_interval: 0s
  max_connections: 3
  max_idle_connections: 3
target:
  data_source_name: 'mysql://${EXPORTER_USERNAME}:${EXPORTER_PASSWORD}@tcp(${EXPORTER_HOSTNAME}:3306)/mysql'
  collectors:
    - mysql
collector_files:
  - "/etc/sql_exporter/*.collector.yml"
