name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        VERSION=$( cat VERSION )
        docker build . --file Dockerfile --tag sql_exporter:local-$VERSION
